// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYZzn7bUG-UWQg-0IZiEg4oPzp1BCBsgE',
    appId: '1:251819963155:web:d383c7096ed311a10ca0e6',
    messagingSenderId: '251819963155',
    projectId: 'salestask-344a0',
    authDomain: 'salestask-344a0.firebaseapp.com',
    storageBucket: 'salestask-344a0.appspot.com',
    measurementId: 'G-SLFQ18Q5R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkWSFwZZYgeHgTH_QceMzUgqtW90gKK4U',
    appId: '1:251819963155:android:9ec9b70b9b9c80320ca0e6',
    messagingSenderId: '251819963155',
    projectId: 'salestask-344a0',
    storageBucket: 'salestask-344a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKirAGsurFKk8WhAN7RtO1iY8OA6BtxaI',
    appId: '1:251819963155:ios:fb489de9791424130ca0e6',
    messagingSenderId: '251819963155',
    projectId: 'salestask-344a0',
    storageBucket: 'salestask-344a0.appspot.com',
    iosBundleId: 'com.example.xianinfotechTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKirAGsurFKk8WhAN7RtO1iY8OA6BtxaI',
    appId: '1:251819963155:ios:fb489de9791424130ca0e6',
    messagingSenderId: '251819963155',
    projectId: 'salestask-344a0',
    storageBucket: 'salestask-344a0.appspot.com',
    iosBundleId: 'com.example.xianinfotechTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYZzn7bUG-UWQg-0IZiEg4oPzp1BCBsgE',
    appId: '1:251819963155:web:829dc9107b14df470ca0e6',
    messagingSenderId: '251819963155',
    projectId: 'salestask-344a0',
    authDomain: 'salestask-344a0.firebaseapp.com',
    storageBucket: 'salestask-344a0.appspot.com',
    measurementId: 'G-GGYWD17L3G',
  );
}
